### ISSUE TITLE
didn't find the paper

### ISSUE THREAD

**Issue by wh-isper** [lennart-maack/domain_adaptation#1]
Dear, author! Could you please provide the link of this paper **_Unsupervised Domain Adaptation for Colon Polyp Segmentation using Pixel Level Contrastive Learning_** ? I didn't find it

**Comment by lennart-maack** [comment]
Hey whi-sper, thanks for your question! There is actually no paper to this repo.

**Comment by wh-isper** [comment]
Thanks for your reply!
